"""Atlassian Document Format (ADF) builders for Jira Cloud (api/v3).

Jira Cloud's REST API v3 requires rich-text fields (description, comment body)
to be ADF JSON, not plain strings or wiki markup. These helpers build valid ADF
documents so every ticket and comment created by the pipeline renders correctly.

Reference shape:
    {"version": 1, "type": "doc", "content": [ <block nodes> ]}
"""
from __future__ import annotations

from typing import Any


def text(value: str, marks: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    node: dict[str, Any] = {"type": "text", "text": value}
    if marks:
        node["marks"] = marks
    return node


def strong(value: str) -> dict[str, Any]:
    return text(value, marks=[{"type": "strong"}])


def link(value: str, href: str) -> dict[str, Any]:
    return text(value, marks=[{"type": "link", "attrs": {"href": href}}])


def code(value: str) -> dict[str, Any]:
    return text(value, marks=[{"type": "code"}])


def paragraph(*nodes: dict[str, Any]) -> dict[str, Any]:
    return {"type": "paragraph", "content": list(nodes)}


def heading(value: str, level: int = 3) -> dict[str, Any]:
    return {
        "type": "heading",
        "attrs": {"level": level},
        "content": [text(value)],
    }


def bullet_list(items: list[list[dict[str, Any]]]) -> dict[str, Any]:
    return {
        "type": "bulletList",
        "content": [
            {"type": "listItem", "content": [{"type": "paragraph", "content": item}]}
            for item in items
        ],
    }


def code_block(value: str, language: str | None = None) -> dict[str, Any]:
    node: dict[str, Any] = {
        "type": "codeBlock",
        "content": [{"type": "text", "text": value}],
    }
    if language:
        node["attrs"] = {"language": language}
    return node


def rule() -> dict[str, Any]:
    return {"type": "rule"}


def doc(*blocks: dict[str, Any]) -> dict[str, Any]:
    """Wrap block nodes into a complete ADF document."""
    return {"version": 1, "type": "doc", "content": list(blocks)}


def plain_doc(message: str) -> dict[str, Any]:
    """Shortcut: a single-paragraph ADF doc from plain text."""
    return doc(paragraph(text(message)))


def release_ticket_description(
    *,
    product: str,
    version: str,
    release_date: str,
    classification: str,
    summary: str,
    analysis: str,
    release_url: str | None = None,
) -> dict[str, Any]:
    """Build a structured ADF description for a AWS DriftGuard ticket."""
    facts: list[list[dict[str, Any]]] = [
        [strong("Product: "), text(product)],
        [strong("Version: "), text(version)],
        [strong("Release date: "), text(release_date)],
        [strong("Change type: "), code(classification)],
    ]
    if release_url:
        facts.append([strong("Release notes: "), link(release_url, release_url)])

    blocks = [
        heading("Release Summary", level=3),
        paragraph(text(summary)),
        heading("Release Details", level=3),
        bullet_list(facts),
        heading("Change Analysis", level=3),
        paragraph(text(analysis)),
        rule(),
        paragraph(
            text("Auto-generated by the AWS DriftGuard pipeline.",
                 marks=[{"type": "em"}])
        ),
    ]
    return doc(*blocks)


def comment_with_timestamp(message: str, timestamp: str, pr_url: str | None = None) -> dict[str, Any]:
    """Build an ADF comment with a session timestamp and optional PR link."""
    blocks = [paragraph(strong("AWS DriftGuard pipeline run — "), text(timestamp))]
    blocks.append(paragraph(text(message)))
    if pr_url:
        blocks.append(paragraph(strong("Pull request: "), link(pr_url, pr_url)))
    return doc(*blocks)
